# apps/backend/Dockerfile
FROM node:20-alpine AS development
WORKDIR /app
CMD ["echo", "Contenedor dev listo"]

# Aquí está la palabra mágica que tu docker-compose estaba buscando
FROM node:20-alpine AS production 
WORKDIR /app
CMD ["echo", "Contenedor prod listo"]