name: Observatorio UX - CI Gate

on:
  pull_request:
    branches: [ main ]

jobs:
  auditoria-tecnica:
    name: Validacion de Codigo y Contratos Zod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      # 1. Le enseñamos al servidor de GitHub qué es pnpm
      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # 2. Cambiamos el caché de npm a pnpm

      # 3. pnpm install --frozen-lockfile es el equivalente exacto de "npm ci"
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      # 4. Así se ejecutan scripts en paquetes específicos con pnpm
      - name: Compilar contratos compartidos (shared-types)
        run: pnpm --filter shared-types run build

      # 5. Así se ejecuta un comando en todos los proyectos del monorepo a la vez
      - name: Verificacion de tipos en todo el monorepo
        run: pnpm -r run build